repos:
-   repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/pyCQA/flake8
    rev: 7.1.0
    hooks:
    - id: flake8
-   repo: https://github.com/numpy/numpydoc
    rev: v1.10.0
    hooks:
    - id: numpydoc-validation
      alias: numpydoc
