"""
Functionality for reading recently-recorded data in a plan.

This is intended to provide an easy-to-use way to access data and
metadata generated by a run inside a plan, like for saving a small
file locally with some data, for more immediate use, or doing a conditional
inside a plan, based on the previous run's results.

Note that the data recorded and used here is not permanent, nor complete in
most cases (like with area detectors, that save directly to Ibira, and so doesn't
go through Bluesky at all). To access those, the data saved at Ibira should be used instead.

An example on how to use these is provided below:

.. code-block:: python

    from bluesky import RunEngine
    from bluesky.plans import count

    from ophyd.sim import hw

    from sophys.common.plans.annotated_default_plans import DETECTORS_TYPE, MD_TYPE
    from sophys.common.utils.data_access import get_run_data, setup_databroker


    def example_plan(detectors: DETECTORS_TYPE, *, num=10, md: MD_TYPE = None):
        md = md or {}
        _md = {**md, "my_other_thing_key": "my_other_thing_value"}

        uid = (yield from count(detectors, num=num, delay=0, md=_md))

        try:
            data_from_count = get_run_data(uid, _md)
        except Exception:
            pass
        else:
            # Do some (basic) stuff with our data!
            data_from_count = data_from_count.primary.read()

            data_med = float(sum(data_from_count.rand) / len(data_from_count.rand))
            print("Median (n={}): {:.5f}".format(num, data_med))

            if abs(data_med - 0.5) > 0.0025:
                new_num = num * 2
                print("Not enough data! Will retry with n={}".format(new_num))

                yield from example_plan(detectors, num=new_num, md=md)


    if __name__ == "__main__":
        RE = RunEngine({})

        # This may be ommited, and all it will do is not do the calculation stuff at the end.
        setup_databroker(RE)

        rand = hw().rand
        rand.kind = "hinted"     # Specific to the simulated random device
        rand.start_simulation()  # Specific to the simulated random device

        RE(example_plan([rand]))

You can also setup the databroker on a single plan, from inside it, making it
independent from the RunEngine's configuration, like so:

.. code-block:: python

    from bluesky import RunEngine
    from bluesky.plans import count

    from ophyd.sim import hw

    from databroker.v2 import temp

    from sophys.common.plans.annotated_default_plans import DETECTORS_TYPE, MD_TYPE
    from sophys.common.utils.data_access import setup_databroker


    def example_plan(detectors: DETECTORS_TYPE, *, num=10, md: MD_TYPE = None):
        md = md or {}
        _md = {**md, "my_other_thing_key": "my_other_thing_value"}

        db = temp()

        # Make all Bluesky events go to the databroker catalog
        token = (yield from bps.subscribe("all", db.v1.insert))

        uid = (yield from count(detectors, num=num, delay=0, md=_md))

        # Remove the databroker catalog callback
        yield from bps.unsubscribe(token)

        data_from_count = db[uid]

        # Do some (basic) stuff with our data!
        data_from_count = data_from_count.primary.read()

        data_med = float(sum(data_from_count.rand) / len(data_from_count.rand))
        print("Median (n={}): {:.5f}".format(num, data_med))

        if abs(data_med - 0.5) > 0.0025:
            new_num = num * 2
            print("Not enough data! Will retry with n={}".format(new_num))

            yield from example_plan(detectors, num=new_num, md=md)


    if __name__ == "__main__":
        RE = RunEngine({})

        # No need to call setup_databroker, but doing so won't break anything.
        setup_databroker(RE)

        rand = hw().rand
        rand.kind = "hinted"     # Specific to the simulated random device
        rand.start_simulation()  # Specific to the simulated random device

        RE(example_plan([rand]))
"""

import logging

from bluesky import RunEngine


__global_dbs = {}


def get_run_data(run_uid: str, run_metadata: dict, /):
    """
    Get the result data from the run with the given UID.

    Usually only the most recent run(s) are available via this method, so
    for more permanent data, access the relevant Ibira path.

    Parameters
    ----------
    run_uid : str
        The UID of the run. Corresponds to the start document's UID.
    run_metadata : dict
        The metadata of that run. Usually the final ``md`` dict.

    Raises
    ------
    Exception
        If no data is available to search for. This is possibly due to not having
        called :func:`sophys.common.utils.data_access.setup_databroker` before-hand.
    KeyError
        The given UID does not map to a run in the broker.
    """
    global __global_dbs

    if len(__global_dbs) == 0:
        raise Exception(
            "No data available in Databroker. Did you call `sophys.common.utils.data_access.setup_databroker`?"
        )

    for re, (db, _) in __global_dbs.items():
        try:
            return db[run_uid]
        except KeyError:
            pass

    raise KeyError("No run with the given uid was found.")


def setup_databroker(run_engine: RunEngine):
    """
    Configure a Databroker instance in ``run_engine``.

    This is necessary for us to be able to access the most recent run data directly
    from a plan, in order to make runtime decisions on the plan's course.
    """
    global __global_dbs
    if run_engine in __global_dbs:
        return

    try:
        from databroker.v2 import temp
    except ImportError as e:
        logging.error("Databroker is not available in the current environment!")
        raise e

    db = temp()
    sub_ticket = run_engine.subscribe(db.v1.insert)
    __global_dbs[run_engine] = (db, sub_ticket)
